backend:
  name: git-gateway
  branch: main
  identity_url: https://illustrious-sunflower-e0f144.netlify.app
  identity_roles:
    - admin

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: news
    label: 最新消息
    folder: "news"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "日期", name: "date", widget: "datetime" }
      - { label: "內容", name: "body", widget: "markdown" }
      - { label: "封面圖片", name: "thumbnail", widget: "image" }
