backend:
  name: github
  repo: Robin568568/qiming-site # ← 替換成你的 GitHub 倉庫
  branch: main

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: news
    label: 最新消息
    folder: "news"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "日期", name: "date", widget: "datetime" }
      - { label: "內容", name: "body", widget: "markdown" }
      - { label: "封面圖片", name: "thumbnail", widget: "image" }
